/*
 * This file is part of the "ModuleSystem" project.
 *
 * (c) Nazir Khusnutdinov <nazir@nazir.pro>
 *
 * Creating a "COMTRADE" user for a project "COMTRADE"
 * Создание пользователя "COMTRADE" для проекта "COMTRADE"
 */

SET CLIENT_ENCODING TO 'UTF8';

SET SESSION ROLE role_dev;

DO $BODY$
BEGIN
   -- DROP ROLE IF EXISTS COMTRADE;
   IF NOT EXISTS (SELECT * FROM pg_catalog.pg_user WHERE usename = 'COMTRADE') THEN
      CREATE ROLE COMTRADE;
   END IF;
END $BODY$;
ALTER ROLE COMTRADE RESET ALL;
ALTER ROLE COMTRADE LOGIN;
-- ALTER ROLE COMTRADE SUPERUSER CREATEDB CREATEROLE REPLICATION;
ALTER ROLE COMTRADE PASSWORD 'COMTRADE';
ALTER ROLE COMTRADE VALID UNTIL 'infinity'; -- Make a password valid forever
-- ALTER ROLE COMTRADE VALID UNTIL '2099-12-31 00:00:00';
-- ALTER ROLE COMTRADE CONNECTION LIMIT -1;
-- ALTER ROLE COMTRADE CONNECTION LIMIT 3;
-- UPDATE pg_authid SET rolcatupdate=true WHERE OID=25054::oid

-- REVOKE ALL PRIVILEGES FROM COMTRADE CASCADE;
-- REVOKE role_dev FROM COMTRADE;
GRANT role_owner TO COMTRADE;

COMMENT ON ROLE COMTRADE IS 'User for project "COMTRADE"';

RESET ROLE;
